language: java

jdk:
  - openjdk8

os:
  - linux

cache:
  directories:
    - $HOME/.m2/repository/

stages:
  - name: build
    if: branch = master

jobs:
  include:
    - stage: build
      name: Maven Clean install
      script:
        - mvn clean install
