name: Maven Build Master

on:
  push:
    branches:
      - ci-cd
      - master

jobs:
  build:
    environment: maven_build_release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Maven
        run: ./.scripts/configure-maven.sh
      - name: Setup GPG
        run: ./.scripts/setup-gpg.sh
        env:
          GPG_SIGNING_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          GPG_PWD: ${{ secrets.GPG_PWD }}
      - name: Build and Publish Project
        run: ./.scripts/publish.sh
        env:
          OSSRH_TOKEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_KEY: ${{ secrets.GPG_KEY }}
          GPG_PWD: ${{ secrets.GPG_PWD }}
